version: "3.9"
services:
    web:
        build: 
          context: .
        ports:
          - "8080:80"
          - "4443:443"
        env_file:
          - .env
        environment:
          ASPNETCORE_ENVIRONMENT: Development
          Database__ConnectionString: "${CONNECTION_STRING}"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
          - "1433:1433"
        env_file:
          - .env
        environment:
            SA_PASSWORD: "${SQL_PASSWORD}"
            ACCEPT_EULA: "Y"
        volumes:
          - ./Database:/scripts
