name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/recipe-manager-api

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'recipe-manager-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cbff4487b1d9463fb074ca6bc62c8d91 }}
        package: ${{env.DOTNET_ROOT}}/recipe-manager-api 
